package com.uca.dynamicgam.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 19 11:43:58 CET 2016
// ---------------------------------------------------------------------
public interface GamCellVO extends ViewObject
{
    void filterByRowKey(Long rowKey);
}

