package com.uca.dynamicgam.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 15 12:18:35 CET 2017
// ---------------------------------------------------------------------
public interface GamRowsVO extends ViewObject
{
  void setCurrentByRowKey(Long rowKey);

  void deleteByRowKey(Long rowKey);
}

