package com.uca.dynamicgam.model.vo.common;

import java.util.List;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 27 11:14:48 CEST 2017
// ---------------------------------------------------------------------
public interface GamRewardsStatsVO extends ViewObject {
    List getNewRewards();
}

