package com.uca.dynamicgam.model.vo.common;

import com.uca.dynamicgam.model.beans.TableRow;

import java.util.List;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:18:55 CET 2016
// ---------------------------------------------------------------------
public interface GamTablesVO extends ViewObject {
    List<TableRow> buildTableContent();

  void queryTableAndColumns(String schema, String table);
}

