package com.uca.dynamicgam.model.am.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 15 12:12:51 CET 2017
// ---------------------------------------------------------------------
public interface DynamicGamAM extends ApplicationModule {
  void createDynamicRowAndColumns();

    List getAssignedRoles(String viewObject);

    void modifyRoles(String viewObject, List newAssignedRoles);

    List setUserAndCommit();
}

