CREATE OR REPLACE PACKAGE PKG_GAM_USER AS 

  PROCEDURE SET_USER (USER_IN VARCHAR2);
  
  FUNCTION GET_USER RETURN VARCHAR2;

END PKG_GAM_USER;
/


CREATE OR REPLACE PACKAGE BODY PKG_GAM_USER AS 
  
  CURRENTUSER VARCHAR2(50);
  
  PROCEDURE SET_USER (USER_IN VARCHAR2) IS 
  BEGIN
    CURRENTUSER := USER_IN;
  END;
  
  FUNCTION GET_USER RETURN VARCHAR2 IS
  BEGIN
    RETURN CURRENTUSER;
  END;

END PKG_GAM_USER;
/
