package com.uca.dynamicgam.model.vo;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:40:25 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamColumnsVORowImpl extends ViewRowImpl {
    public static final int ENTITY_GAMCOLUMNSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ColumnName,
        TableName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COLUMNNAME = AttributesEnum.ColumnName.index();
    public static final int TABLENAME = AttributesEnum.TableName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GamColumnsVORowImpl() {
    }

    /**
     * Gets GamColumnsEO entity object.
     * @return the GamColumnsEO
     */
    public EntityImpl getGamColumnsEO() {
        return (EntityImpl) getEntity(ENTITY_GAMCOLUMNSEO);
    }

    /**
     * Gets the attribute value for COLUMN_NAME using the alias name ColumnName.
     * @return the COLUMN_NAME
     */
    public String getColumnName() {
        return (String) getAttributeInternal(COLUMNNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COLUMN_NAME using the alias name ColumnName.
     * @param value value to set the COLUMN_NAME
     */
    public void setColumnName(String value) {
        setAttributeInternal(COLUMNNAME, value);
    }

    /**
     * Gets the attribute value for TABLE_NAME using the alias name TableName.
     * @return the TABLE_NAME
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TABLE_NAME using the alias name TableName.
     * @param value value to set the TABLE_NAME
     */
    public void setTableName(String value) {
        setAttributeInternal(TABLENAME, value);
    }
}

