package com.uca.dynamicgam.model.vo;

import com.uca.dynamicgam.model.vo.base.DynamicGamBaseVOImpl;
import com.uca.dynamicgam.model.vo.common.GamCellVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:17:20 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamCellVOImpl extends DynamicGamBaseVOImpl implements GamCellVO {
    /**
     * This is the default constructor (do not remove).
     */
    public GamCellVOImpl() {
    }

    /**
     * Returns the variable value for bind_rowKey.
     * @return variable value for bind_rowKey
     */
    public Long getbind_rowKey() {
        return (Long) ensureVariableManager().getVariableValue("bind_rowKey");
    }

    /**
     * Sets <code>value</code> for variable bind_rowKey.
     * @param value value to bind as bind_rowKey
     */
    public void setbind_rowKey(Long value) {
        ensureVariableManager().setVariableValue("bind_rowKey", value);
    }
    
    public void filterByRowKey(Long rowKey){
        setbind_rowKey(rowKey);
        executeQuery();
    }
}

