package com.uca.dynamicgam.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:40:25 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamColumnsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GamColumnsVOImpl() {
    }

    /**
     * Returns the variable value for bind_tableName.
     * @return variable value for bind_tableName
     */
    public String getbind_tableName() {
        return (String) ensureVariableManager().getVariableValue("bind_tableName");
    }

    /**
     * Sets <code>value</code> for variable bind_tableName.
     * @param value value to bind as bind_tableName
     */
    public void setbind_tableName(String value) {
        ensureVariableManager().setVariableValue("bind_tableName", value);
    }
}

