package com.uca.dynamicgam.model.vo;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 22 11:20:07 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamHistoryVORowImpl extends ViewRowImpl {

    public static final int ENTITY_GAMHISTORYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        IdHistory,
        UserId,
        Operation,
        HistoryTs,
        Rewarded,
        TruncDate,
        TableName,
        ColumnName,
        GamUsersVO,
        OperationsLOV,
        YesNoLOV;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDHISTORY = AttributesEnum.IdHistory.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int OPERATION = AttributesEnum.Operation.index();
    public static final int HISTORYTS = AttributesEnum.HistoryTs.index();
    public static final int REWARDED = AttributesEnum.Rewarded.index();
    public static final int TRUNCDATE = AttributesEnum.TruncDate.index();
    public static final int TABLENAME = AttributesEnum.TableName.index();
    public static final int COLUMNNAME = AttributesEnum.ColumnName.index();
    public static final int GAMUSERSVO = AttributesEnum.GamUsersVO.index();
    public static final int OPERATIONSLOV = AttributesEnum.OperationsLOV.index();
    public static final int YESNOLOV = AttributesEnum.YesNoLOV.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GamHistoryVORowImpl() {
    }

    /**
     * Gets GamHistoryEO entity object.
     * @return the GamHistoryEO
     */
    public EntityImpl getGamHistoryEO() {
        return (EntityImpl) getEntity(ENTITY_GAMHISTORYEO);
    }

    /**
     * Gets the attribute value for ID_HISTORY using the alias name IdHistory.
     * @return the ID_HISTORY
     */
    public Long getIdHistory() {
        return (Long) getAttributeInternal(IDHISTORY);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for OPERATION using the alias name Operation.
     * @return the OPERATION
     */
    public String getOperation() {
        return (String) getAttributeInternal(OPERATION);
    }

    /**
     * Gets the attribute value for HISTORY_TS using the alias name HistoryTs.
     * @return the HISTORY_TS
     */
    public Timestamp getHistoryTs() {
        return (Timestamp) getAttributeInternal(HISTORYTS);
    }

    /**
     * Gets the attribute value for REWARDED using the alias name Rewarded.
     * @return the REWARDED
     */
    public String getRewarded() {
        return (String) getAttributeInternal(REWARDED);
    }

    /**
     * Sets <code>value</code> as attribute value for REWARDED using the alias name Rewarded.
     * @param value value to set the REWARDED
     */
    public void setRewarded(String value) {
        setAttributeInternal(REWARDED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TruncDate.
     * @return the TruncDate
     */
    public Date getTruncDate() {
        return (Date) getAttributeInternal(TRUNCDATE);
    }

    /**
     * Gets the attribute value for TABLE_NAME using the alias name TableName.
     * @return the TABLE_NAME
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }

    /**
     * Gets the attribute value for COLUMN_NAME using the alias name ColumnName.
     * @return the COLUMN_NAME
     */
    public String getColumnName() {
        return (String) getAttributeInternal(COLUMNNAME);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GamUsersVO.
     */
    public RowSet getGamUsersVO() {
        return (RowSet) getAttributeInternal(GAMUSERSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OperationsLOV.
     */
    public RowSet getOperationsLOV() {
        return (RowSet) getAttributeInternal(OPERATIONSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> YesNoLOV.
     */
    public RowSet getYesNoLOV() {
        return (RowSet) getAttributeInternal(YESNOLOV);
    }
}

