package com.uca.dynamicgam.model.vo;

import com.uca.dynamicgam.model.vo.base.DynamicGamBaseVOImpl;
import com.uca.dynamicgam.model.vo.common.GamRowsVO;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:17:12 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamRowsVOImpl extends DynamicGamBaseVOImpl implements GamRowsVO {
    /**
     * This is the default constructor (do not remove).
     */
    public GamRowsVOImpl() {
    }

    public void setCurrentByRowKey(Long rowKey) {
        Row[] byKey = this.findByKey(new Key(new Object[] { rowKey }), 1);
        if (byKey != null && byKey.length > 0) {
            this.setCurrentRow(byKey[0]);
        }
    }

    public void deleteByRowKey(Long rowKey) {
        Row[] byKey = this.findByKey(new Key(new Object[] { rowKey }), 1);
        if (byKey != null && byKey.length > 0) {
            GamRowsVORowImpl deleteRow = (GamRowsVORowImpl) byKey[0];
            Row[] cells = deleteRow.getGamCell().getAllRowsInRange();
            for (Row cell : cells) {
                cell.remove();
            }
            deleteRow.remove();
        }
    }
}

