package com.uca.dynamicgam.model.vo;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:17:12 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamRowsVORowImpl extends ViewRowImpl {
    public static final int ENTITY_GAMROWSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RowKey,
        TableName,
        GamCell;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROWKEY = AttributesEnum.RowKey.index();
    public static final int TABLENAME = AttributesEnum.TableName.index();
    public static final int GAMCELL = AttributesEnum.GamCell.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GamRowsVORowImpl() {
    }

    /**
     * Gets GamRowsEO entity object.
     * @return the GamRowsEO
     */
    public EntityImpl getGamRowsEO() {
        return (EntityImpl) getEntity(ENTITY_GAMROWSEO);
    }

    /**
     * Gets the attribute value for ROW_KEY using the alias name RowKey.
     * @return the ROW_KEY
     */
    public Long getRowKey() {
        return (Long) getAttributeInternal(ROWKEY);
    }

    /**
     * Sets <code>value</code> as attribute value for ROW_KEY using the alias name RowKey.
     * @param value value to set the ROW_KEY
     */
    public void setRowKey(Long value) {
        setAttributeInternal(ROWKEY, value);
    }

    /**
     * Gets the attribute value for TABLE_NAME using the alias name TableName.
     * @return the TABLE_NAME
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TABLE_NAME using the alias name TableName.
     * @param value value to set the TABLE_NAME
     */
    public void setTableName(String value) {
        setAttributeInternal(TABLENAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GamCell.
     */
    public RowIterator getGamCell() {
        return (RowIterator) getAttributeInternal(GAMCELL);
    }
}

