package com.uca.dynamicgam.model.vo;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 14:14:57 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GamTablesVORowImpl extends ViewRowImpl {
    public static final int ENTITY_GAMTABLESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TableName,
        Schema,
        GamColumns,
        GamRows;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TABLENAME = AttributesEnum.TableName.index();
    public static final int SCHEMA = AttributesEnum.Schema.index();
    public static final int GAMCOLUMNS = AttributesEnum.GamColumns.index();
    public static final int GAMROWS = AttributesEnum.GamRows.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GamTablesVORowImpl() {
    }

    /**
     * Gets GamTablesEO entity object.
     * @return the GamTablesEO
     */
    public EntityImpl getGamTablesEO() {
        return (EntityImpl) getEntity(ENTITY_GAMTABLESEO);
    }

    /**
     * Gets the attribute value for TABLE_NAME using the alias name TableName.
     * @return the TABLE_NAME
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TABLE_NAME using the alias name TableName.
     * @param value value to set the TABLE_NAME
     */
    public void setTableName(String value) {
        setAttributeInternal(TABLENAME, value);
    }

    /**
     * Gets the attribute value for SCHEMA using the alias name Schema.
     * @return the SCHEMA
     */
    public String getSchema() {
        return (String) getAttributeInternal(SCHEMA);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEMA using the alias name Schema.
     * @param value value to set the SCHEMA
     */
    public void setSchema(String value) {
        setAttributeInternal(SCHEMA, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GamColumns.
     */
    public RowIterator getGamColumns() {
        return (RowIterator) getAttributeInternal(GAMCOLUMNS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link GamRows.
     */
    public RowIterator getGamRows() {
        return (RowIterator) getAttributeInternal(GAMROWS);
    }
}

