package com.uca.dynamicgam.model.vo;

import com.uca.dynamicgam.model.vo.base.DynamicGamBaseVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 22 11:18:10 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OperationsCountVOImpl extends DynamicGamBaseVOImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OperationsCountVOImpl() {
    }
}

