package com.uca.dynamicgam.model.vo;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 23 12:03:14 CEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TablesByUserVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Schema,
        TableName;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SCHEMA = AttributesEnum.Schema.index();
    public static final int TABLENAME = AttributesEnum.TableName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TablesByUserVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Schema.
     * @return the Schema
     */
    public String getSchema() {
        return (String) getAttributeInternal(SCHEMA);
    }

    /**
     * Gets the attribute value for the calculated attribute TableName.
     * @return the TableName
     */
    public String getTableName() {
        return (String) getAttributeInternal(TABLENAME);
    }
}

